### ISSUE TITLE
[BUG]: Importing las-js fails on node v10.x

### ISSUE THREAD

**Issue by nDevised** [laslibs/las-js#41]
**Describe the bug**
Processing file: C:/Users/labadmin/Documents/CSTWeb/(10)77502S_C1L1_02000_00000.las
Processing file: C:/Users/labadmin/Documents/CSTWeb/(11)81604S_C1L1_08000_04000.las
Processing file: C:/Users/labadmin/Documents/CSTWeb/03210N_C1R1_16000_20000_cut_small.las    
Processing file: C:/Users/labadmin/Documents/CSTWeb/77902S_C1L1_L1L2_20000_16000.las
TypeError: Cannot read properties of undefined (reading 'split')
    at Las.<anonymous> (C:\Users\labadmin\Documents\GitHub\las-js-test\node_modules\las-js\dist\index.js:280:57)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\labadmin\Documents\GitHub\las-js-test\node_modules\las-js\dist\index.js:5:58)

I am having this error when the las file is loaded with a valid path. It seems like something to do with the blobstring part of it. I am not sure however why it occurs. Please let me know how I can address this issue. Thanks

**To Reproduce**
1. Import '...'
2. Run '....'

**Expected behavior**

**Screenshots**
![image](https://github.com/laslibs/las-js/assets/90827405/fe66ee7b-5478-4367-ac26-2790cb642566)

Here is a screenshot of my code where I am using it:
![image](https://github.com/laslibs/las-js/assets/90827405/e883e620-faad-43a9-9f9e-f18ab89ad760)
![image](https://github.com/laslibs/las-js/assets/90827405/764cc015-2105-49e9-a520-1fbb956f2486)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Node Version: 9.6.7

**Comment by iykekings** [comment]
Hello @nDevised sorry for replying late. Can you post the las file?

**Comment by iykekings** [comment]
And what version of las-js are you using?

**Comment by nDevised** [comment]
> And what version of las-js are you using?

Using the latest version npm has to offer
